### ISSUE TITLE
Ideas for application initial setup?

### ISSUE THREAD

**Issue by itsrennyman** [itsrennyman/aurora#19]
Currently, Aurora needs a "manual" seeding procedure with some Knex seed files. 

It would be nice to implement some sort of initial setup to make the up and running process much faster!

The process on initialization currently is simple:
- Table Creation
- FIrst User Creation

Some CLI setup for example. Any ideas?

**Comment by tracker1** [comment]
Related, would be good to have this automated as part of the service startup as well as a docker-compose file for getting up and running quickly.

**Comment by itsrennyman** [comment]
In the last release, I've implemented the `npm run aurora:setup` command which guides you to the first user creation!

Yes, the Dockerfile is currently in the next development roadmap. I will be inserted into the repository, I will update the docs also with a docker-compose example.

**Comment by itsrennyman** [comment]
> Related, would be good to have this automated as part of the service startup as well as a docker-compose file for getting up and running quickly.

@tracker1 this new v0.5 release has the dockerfile support. There is also a sample docker-compose implementation In the documentation.

Enjoy!
