### ISSUE TITLE
What data can I show?

### ISSUE THREAD

**Issue by itsrennyman** [itsrennyman/aurora#2]
Hi!

Currently, Aurora Supports some Graph Displaying data, but I have poor ideas about what next data could be displayed.

Any suggestions?

**Comment by akatsukilevi** [comment]
Perhaps user interactions?
How much time the person kept on the page, if the person clicked on any link
Would be cool to also allow to add custom trackers, like let's say, on a e-commerce, i could implement a tracker to see how many ppl are adding products on the cart and how many are only looking

**Comment by thomas-br** [comment]
> Perhaps user interactions?
> 
> How much time the person kept on the page, if the person clicked on any link
> 
> Would be cool to also allow to add custom trackers, like let's say, on a e-commerce, i could implement a tracker to see how many ppl are adding products on the cart and how many are only looking

Agree. I think event tracking similar to how [matomo](https://matomo.org/docs/event-tracking/) is doing it would definitely be a benefit. 

Additionally having an Option to track frontend errors on the web clients would also be helpful imo

**Comment by akatsukilevi** [comment]
> Agree. I think event tracking similar to how [matomo](https://matomo.org/docs/event-tracking/) is doing it would definitely be a benefit.
> 
> Additionally having an Option to track frontend errors on the web clients would also be helpful imo

This would be perfect, and the front-end errors one could help to minimize bugs and problems on the end-user

**Comment by itsrennyman** [comment]
The page view time I think is quite useful, you can do a lot of statistics with that.
For the user interactions yes, is a good starting point, I will think about that and inserted in my roadmap.

Doubt comes to me for error tracking, isn't it a job more for Sentry?

Thanks for your feedback!

**Comment by itsrennyman** [comment]
I have implemented a timing function based on the page view duration.

You can see it on the: [tracker](https://github.com/itsrennyman/aurora/blob/main/tracker/aurora.js#L43)

After some research, I finally concluded that the "visibilitychange" event works most of the time with the sendBeacon event even on mobile web browsers.
Some special cases do not work as well, but it becomes a less serious problem for the law of large numbers. 

Do you know some other options for that?

**Comment by akatsukilevi** [comment]
As far as my JS knowledge, this implementation is the best one, yet i'd change the listened event name matching the browser
As MDN shows as example(Source [Here](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API))
```js
if (typeof document.hidden !== "undefined") { // Opera 12.10 and Firefox 18 and later support
  hidden = "hidden";
  visibilityChange = "visibilitychange";
} else if (typeof document.msHidden !== "undefined") {
  hidden = "msHidden";
  visibilityChange = "msvisibilitychange";
} else if (typeof document.webkitHidden !== "undefined") {
  hidden = "webkitHidden";
  visibilityChange = "webkitvisibilitychange";
}
```
This would ensure a better compatibility between browsers

**Comment by mauriciobc** [comment]
Heatmaps! This is one of the most useful tools for user experience professionals.

**Comment by ro-savage** [comment]
Nice work putting this together. I would say by far the simple and most useful would be UTM tags.

**Comment by itsrennyman** [comment]
> Heatmaps! This is one of the most useful tools for user experience professionals.

Yes, I think so too, at the moment I'm working on the implementation of a heatmap, probably in the next release it will be available.

**Comment by itsrennyman** [comment]
> Nice work putting this together. I would say by far the simple and most useful would be UTM tags.

Utm tags are a good idea, it might be valid to insert them, I will consider this possibility.
