### ISSUE TITLE
How to set a base url

### ISSUE THREAD

**Issue by IngoRauschenberg** [itsrennyman/aurora#67]
Hello again,

sorry to bother you, but I still have a question about my test installation.

This is my setup:
I have the api running on port 5000 and the ui running on port 3000 on a test-server.
I have an apache and have defined, that https://mydomain.de/T-auroraapi/ will be forwarded to the test-server on port 5000.
On the same apache I have defined, thad https://mydomain.de/T-auroraui/ will be forwarded to the test-server on port 3000.
In the .env file from the ui I have set 
NEXT_PUBLIC_API_URL=https://mydomain.de/T-auroraapi/

When I call https://mydomain.de/T-auroraapi/ I get
`{"message":"Aurora Analytics API Service","version":"1.0.0"}`
which seems ok to me.

When I call https://mydomain.de/T-auroraui/setup I get the setup page, but it looks like the age didn't work right, because the site didn't uses relative pathes for things like css:
`<link rel="preload" href="/_next/static/css/46bd5a7a3392dce63e4b.css" as="style">`
The above line results in  https://mydomain.de/_next/static/css/46bd5a7a3392dce63e4b.css and not in https://mydomain.de/T-auroraui/_next/static/css/46bd5a7a3392dce63e4b.css

Is it possible that I can configure in the .env file of the ui, which path aurora-ui should use for itself?

best regards
Ingo Rauschenberg

**Comment by itsrennyman** [comment]
Hello!

Maybe nextjs has already some base path feature.

I will do some research about this request. And i will let you know.

**Comment by itsrennyman** [comment]
Closed due to API changes.
