### ISSUE TITLE
Delete websites in the UI

### ISSUE THREAD

**Issue by webmo2001** [itsrennyman/aurora#84]
Hello,
sometimes I create a test website and when the test ended I have to manually delete all the data in the database .
It would be cool to delete websites directly in the user interface.
thx and best regards
Oliver Walter

**Comment by itsrennyman** [comment]
Hi!

Thanks for the issue, I'm taking care of this problem.

**Comment by itsrennyman** [comment]
Hi, this feature is now implemented in the V2 version.

**Comment by webmo2001** [comment]
Great, thank you very much. I am very excited about version V2. Best regards Oliver
